[project]
name = "arc-raiders-tracker"
version = "0.1.0"
description = ""
authors = [
    {name = "Marcos Souza PC casa",email = "antoniomarcus13@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pytest (>=9.0.2,<10.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
